### PR TITLE
ci: give more resources to nightly runs with Kurtosis clean in betweem

### PR DESCRIPTION
**Pull request by h4ck3rk3y**

### CODE REVIEW

**Comment by gbouv** [comment]
@h4ck3rk3y can we close this on? I think everything is fixed post #95. Verifying it with this build but I'm hopeful it will passx https://app.circleci.com/pipelines/github/kurtosis-tech/awesome-kurtosis/466/workflows/eefec36f-c515-4c41-9c1d-2cda8b8ba3a0

**Comment by h4ck3rk3y** [comment]
@gbouv happy for you to close this if the nightly runs build runs

https://app.circleci.com/pipelines/github/kurtosis-tech/awesome-kurtosis?branch=main

Click on "Trigger pipeline" and set should-enable-check-latest-version-workflow to boolean and to true

**Comment by h4ck3rk3y** [comment]
Oh I can see a run already!

**Comment by gbouv** [comment]
Yeah I just re-run the last one that failed :lazy:

**Pull request closed without merging**
